// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionsMVCApp.Data;

#nullable disable

namespace TransactionsMVCApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionsMVCApp.Models.EventoTransaccion", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("EventosTransaccion");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            Descripcion = "Transacción creada",
                            FechaEvento = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoEvento = "Creación",
                            TransaccionId = 1
                        },
                        new
                        {
                            EventoId = 2,
                            Descripcion = "Procesada correctamente",
                            FechaEvento = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoEvento = "Procesamiento",
                            TransaccionId = 2
                        });
                });

            modelBuilder.Entity("TransactionsMVCApp.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNotificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId");

                    b.HasIndex("TransaccionId")
                        .IsUnique();

                    b.ToTable("Notificaciones");

                    b.HasData(
                        new
                        {
                            NotificacionId = 1,
                            EmailCliente = "cliente@test.com",
                            EstadoNotificacion = "Enviada",
                            FechaEnvio = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransaccionId = 2
                        });
                });

            modelBuilder.Entity("TransactionsMVCApp.Models.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("CuentaDestino")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.Property<string>("DetallesAdicionales")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransaccionId");

                    b.ToTable("Transacciones");

                    b.HasData(
                        new
                        {
                            TransaccionId = 1,
                            CuentaDestino = "1234567890123456",
                            DetallesAdicionales = "Pago factura",
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 120.50m,
                            TipoTransaccion = "TransferenciaBancaria"
                        },
                        new
                        {
                            TransaccionId = 2,
                            CuentaDestino = "9999888877776666",
                            DetallesAdicionales = "Compra online",
                            Estado = "Exitosa",
                            FechaCreacion = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaProcesamiento = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 75.00m,
                            TipoTransaccion = "PagoConTarjeta"
                        });
                });

            modelBuilder.Entity("TransactionsMVCApp.Models.EventoTransaccion", b =>
                {
                    b.HasOne("TransactionsMVCApp.Models.Transaccion", "Transaccion")
                        .WithMany("Eventos")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("TransactionsMVCApp.Models.Notificacion", b =>
                {
                    b.HasOne("TransactionsMVCApp.Models.Transaccion", "Transaccion")
                        .WithOne("Notificacion")
                        .HasForeignKey("TransactionsMVCApp.Models.Notificacion", "TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("TransactionsMVCApp.Models.Transaccion", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Notificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
